### PR TITLE
Add transfem.social

### PR DESCRIPTION
**Pull request by ariscript**
transfem.social is a sharkey instance on the fediverse, and it would be great if this extension worked there.
If I need to do anything else to add support, do let me know and I'll be happy to try it out :)

### CODE REVIEW

**Comment by Rexogamer** [comment]
i could be wrong, but i *thought* shinigami only supported masto? TFS uses sharkey, so i'm not sure if anything needs to be done to add sharkey support first

**Comment by starmut** [comment]
I'm not sure how this extension works exactly. I could try and figure it out next week, or if someone can give me some pointers where to add sharkey support. Supporting more fediverse apps is important in this day and age.

**Comment by LimePotato** [comment]
This plugin wouldnt exactly work on *key as key overrides the context menu, see

**Comment by LimePotato** [comment]
This would likely be a feature youd have to implement on the *key frontend side

**Comment by LimePotato** [comment]
and at this point this is something that should be reported to the moderation team of your website so the remote user can get suspended/silenced/etc.

**Comment by ariscript** [comment]
Right, I didn't fully consider the context menu issue. In any case, I didn't want to report any particular user, just be able to see users' reports as I could on other instances - not really an issue for the moderation team.

**Comment by LiEnby** [comment]
it would be extremely weird to find transphobic content on a social site called _transfem.social_ but it could make sense to add for sharkey in general maybe.

**Pull request closed without merging**
