### PR TITLE
privacy improvements

### PR DESCRIPTION
**Pull request by mkljczk**

### CODE REVIEW

**Review by thomasjwebb — APPROVED** [review]

**Comment by Laurelai** [comment]
This is just sad.

**Comment by PrimordialHelios** [comment]
@laurelai over 100 fediverse users disagree with you. you are the minority
https://soc.punktrash.club/notice/9jAa0HBsQ4CdGGOrg0

**Comment by Laurelai** [comment]
Yeah well i can find numbers who agree with me on tumblr and facebook. And you lied and said the creator is a terf. When you lie to manipulate people to agree with you it doesnt count. You even got called on it here.

https://eldritch.cafe/@Sylvhem/102158616925179310 and Sylvhem knows the developer, verifed they were not a terf. You just like lying to stir up drama. Again.

**Comment by Laurelai** [comment]
In fact multiple people in that thread know the developer and verified they are not a terf. You are just saying the developer is so you can incite anger toward your chosen target. This is extremely manipulative, dishonest and wrong. 

If you want to be taken seriously in life you have got to stop lying and stretching the truth to fit your agenda. People see through it eventually.

**Review by mikegogulski — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by Laurelai** [comment]
Since @PrimorialHelios has me blocked and i cant reply to the thread i keep being pinged in ill address
https://github.com/shinigami-eyes/shinigami-eyes/issues/20 this here.

I am not the creator of this software. 

And yes if you block someone they cant reply to threads you created as proven here. 

https://mastodon.starrevolution.org/@Laurelai/102164793372441419

The reason im defending the app creator is simply because i think its the right thing to do, combined with PrimordialHelios' constant lying and manipulation. PS you dont get to say im stalking you when you link me to a mastodon thread you made and i reply to it. Especially since you keep @ing me here. 

What you are is a lying manipulative bully.

**Comment by Laurelai** [comment]
Also heres the plugin having an ace positive page marked green, basically proving they only mark green for trans positive comments and probably dont go outside of that scope https://imgur.com/a/okfYlSy

As for the rest of yall, you really want to join forces with this lying manipulative person? Really? When there are real threats to the trans community when governments keep stripping us of rights this is what you focus your energy on? An app that helps trans people avoid their enemies?

What you are doing, knowingly or not is straight up transphobic.

**Comment by Laurelai** [comment]
Oh look the terfs are using your arguments and also trying to report it as a GDPR violation.

https://terflies.tumblr.com/post/185219205336/httpschromegooglecomwebstorereportijcpiojge

Specifically they cite you @mikegogulski

**Comment by mikegogulski** [comment]
¯\_(ツ)_/¯

**Comment by Laurelai** [comment]
> ¯\_(ツ)_/¯

If fascists started using my words to attack marginalized people id quickly distance myself and think hard about what i was saying. But not you though. Hmm.

**Comment by m4sk1n** [comment]
If fascists started drinking water like me

**Comment by PrimordialHelios** [comment]
Hitler was a vegetarian and dislike smoking

Guess we should eat nothing but meat and cigarettes then

**Comment by solonovamax** [comment]
> @Laurelai over 100 fediverse users disagree with you. you are the minority
https://soc.punktrash.club/notice/9jAa0HBsQ4CdGGOrg0

LUL what the fuck even is fediverse??? I've never heard of that shit before.

**Review by solonovamax — CHANGES_REQUESTED** [review]
stop being stupid lol

**Review by Supernova1750 — APPROVED** [review]

**Comment by kipuyanoo** [comment]
fediverse.party

**Comment by kipuyanoo** [comment]
oh sorry necropost

**Comment by LiEnby** [comment]
> @Laurelai over 100 fediverse users disagree with you. you are the minority https://soc.punktrash.club/notice/9jAa0HBsQ4CdGGOrg0

this pr is un-nuanced, 100 fediverse users might think the t-friendly list is a privacy issue and can potentially out trans people, but still think the transphobic list is fine, (for example) but the pr removes both, a pro-ace page is very likely also pro-trans, that seems obvious. and is still kinda adjacent to LGBT and thus trans people, im not sure why pointing this out means the extension is transphobic,, saying that we marked an asexual page, that is very likely pro-trans and you gave no reason to show why isn't pro-trans, somehow makes it transphobic, makes absolutely no sense,.

a way to opt-out of the pro-trans list makes sense, the transphobic one less so as that kinda defeats the point, but also the way the data is stored, there is basically no way to ever modify the data in the app, from what i understand

**Comment by LiEnby** [comment]
> > @Laurelai over 100 fediverse users disagree with you. you are the minority
> > https://soc.punktrash.club/notice/9jAa0HBsQ4CdGGOrg0
> 
> LUL what the fuck even is fediverse??? I've never heard of that shit before.

a decentralized social media site, the majority of instances of it are run by trans / queer people, so its not as unreasonable as you might think, however i suspect alot of these come down to 'i think including the pro trans list is a privacy issue maybe, but the transphobe one is fine' .. if i had to guess.

**Pull request closed without merging**
